title: Paul Dev Journey
description: My journey as a web developer
theme: minima

minima:
  skin: dark

header_pages:
  - index.md
  - about.md
  ---
---

@import "minima";

/* Your custom styles below */

body {
  background: #ffffff;
  color: #111;
}
