title: PFJ Digital
description: Web Developer Journey | Building in Public 🚀
baseurl: ""
url: "https://paulforj.github.io"

theme: minima

author:
  name: Paul
  email: ikwuegbupaul426@email.com

social_links:
  github: paulforj

header_pages:
  - about.md
